const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./src/routes/*"];
// Ref : https://medium.com/swlh/automatic-api-documentation-in-node-js-using-swagger-dd1ab3c78284

const doc = {
  info: {
    version: "1.0.0",
    title: "Doggo Api",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Client",
      description: "Endpoints",
    },
    {
      name: "Breed",
      description: "Endpoints",
    },
    {
      name: "Consultation",
      description: "Endpoints",
    },
    {
      name: "Disease",
      description: "Endpoints",
    },
    {
      name: "Dog",
      description: "Endpoints",
    },
  ],
  definitions: {
    Clients: [
      {
        id: 1,
        firstname: "testy2",
        lastname: "Schouwey",
        female: false,
        email: "dsad",
        phone: "23232",
        street: "chemin",
        id_locality: 1,
      },
    ],
    Client: {
      id: 1,
      firstname: "testy2",
      lastname: "Schouwey",
      female: false,
      email: "dsad",
      phone: "23232",
      street: "chemin",
      id_locality: 1,
    },
    Breeds: [
      {
        id: 1,
        link:
          "https://www.toutoupourlechien.com/race-de-chien/affenpinscher.html",
        picture:
          "https://static.toutoupourlechien.com/2016/08/Race-de-Chien-Affenpinscher.jpg",
        noun: "Affenpinscher",
        id_category: 2,
        morphotype: "Brachycéphale",
        classification: "Autre",
        min_size_female: 25,
        max_size_female: 30,
        min_size_male: 25,
        max_size_male: 30,
        min_weight_female: 4,
        max_weight_female: 6,
        min_weight_male: 4,
        max_weight_male: 6,
        life_expectancy: 13,
      },
    ],
    Breed: {
      id: 1,
      link:
        "https://www.toutoupourlechien.com/race-de-chien/affenpinscher.html",
      picture:
        "https://static.toutoupourlechien.com/2016/08/Race-de-Chien-Affenpinscher.jpg",
      noun: "Affenpinscher",
      id_category: 2,
      morphotype: "Brachycéphale",
      classification: "Autre",
      min_size_female: 25,
      max_size_female: 30,
      min_size_male: 25,
      max_size_male: 30,
      min_weight_female: 4,
      max_weight_female: 6,
      min_weight_male: 4,
      max_weight_male: 6,
      life_expectancy: 13,
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./server.js");
});
